" Vim color file - jellybeans_my
" Generated by http://bytefluent.com/vivify 2015-07-13
set background=dark
if version > 580
	hi clear
	if exists("syntax_on")
		syntax reset
	endif
endif

set t_Co=256
let g:colors_name = "jellybeans_my"

"hi IncSearch -- no settings --
"hi WildMenu -- no settings --
"hi CTagsMember -- no settings --
"hi CTagsGlobalConstant -- no settings --
"hi Ignore -- no settings --
hi Normal guifg=#d4cbff guibg=#151515 guisp=#151515 gui=NONE ctermfg=189 ctermbg=233 cterm=NONE
"hi CTagsImport -- no settings --
"hi CTagsGlobalVariable -- no settings --
"hi SpellRare -- no settings --
"hi EnumerationValue -- no settings --
"hi Float -- no settings --
"hi Union -- no settings --
"hi Question -- no settings --
"hi WarningMsg -- no settings --
"hi VisualNOS -- no settings --
"hi ModeMsg -- no settings --
"hi EnumerationName -- no settings --
"hi MoreMsg -- no settings --
"hi SpellCap -- no settings --
"hi SpellLocal -- no settings --
"hi DefinedName -- no settings --
"hi LocalVariable -- no settings --
"hi SpellBad -- no settings --
"hi CTagsClass -- no settings --
"hi Underlined -- no settings --
"hi clear -- no settings --
"hi def -- no settings --
hi SignColumn guifg=#c6fee2 guibg=#363548 guisp=#363548 gui=NONE ctermfg=158 ctermbg=238 cterm=NONE
hi SpecialComment guifg=#d3eb85 guibg=NONE guisp=NONE gui=NONE ctermfg=192 ctermbg=NONE cterm=NONE
hi Typedef guifg=#ff4164 guibg=NONE guisp=NONE gui=NONE ctermfg=13 ctermbg=NONE cterm=NONE
hi Title guifg=#fcff57 guibg=NONE guisp=NONE gui=bold ctermfg=227 ctermbg=NONE cterm=bold
hi Folded guifg=#c6fee2 guibg=#363548 guisp=#363548 gui=italic ctermfg=158 ctermbg=238 cterm=NONE
hi PreCondit guifg=#8dffdf guibg=NONE guisp=NONE gui=NONE ctermfg=122 ctermbg=NONE cterm=NONE
hi Include guifg=#8dffdf guibg=NONE guisp=NONE gui=NONE ctermfg=122 ctermbg=NONE cterm=NONE
hi TabLineSel guifg=#4e4b4e guibg=#dcd8f0 guisp=#dcd8f0 gui=italic ctermfg=239 ctermbg=255 cterm=NONE
hi StatusLineNC guifg=#d6d9ee guibg=#090618 guisp=#090618 gui=italic ctermfg=189 ctermbg=234 cterm=NONE
hi NonText guifg=#b9b6ce guibg=#151515 guisp=#151515 gui=NONE ctermfg=146 ctermbg=233 cterm=NONE
hi DiffText guifg=NONE guibg=#3f3f40 guisp=#3f3f40 gui=NONE ctermfg=NONE ctermbg=238 cterm=NONE
hi ErrorMsg guifg=NONE guibg=#901460 guisp=#901460 gui=NONE ctermfg=NONE ctermbg=89 cterm=NONE
hi Debug guifg=#d3eb85 guibg=NONE guisp=NONE gui=NONE ctermfg=192 ctermbg=NONE cterm=NONE
hi PMenuSbar guifg=NONE guibg=#74887f guisp=#74887f gui=NONE ctermfg=NONE ctermbg=66 cterm=NONE
hi Identifier guifg=#a7cfff guibg=NONE guisp=NONE gui=NONE ctermfg=153 ctermbg=NONE cterm=NONE
hi SpecialChar guifg=#d3eb85 guibg=NONE guisp=NONE gui=NONE ctermfg=192 ctermbg=NONE cterm=NONE
hi Conditional guifg=#ff4164 guibg=NONE guisp=NONE gui=NONE ctermfg=13 ctermbg=NONE cterm=NONE
hi StorageClass guifg=#ff7c77 guibg=NONE guisp=NONE gui=NONE ctermfg=210 ctermbg=NONE cterm=NONE
hi Todo guifg=#b9b6ce guibg=NONE guisp=NONE gui=bold ctermfg=146 ctermbg=NONE cterm=bold
hi Special guifg=#d3eb85 guibg=NONE guisp=NONE gui=NONE ctermfg=192 ctermbg=NONE cterm=NONE
hi LineNr guifg=#ad91ac guibg=#151515 guisp=#151515 gui=NONE ctermfg=139 ctermbg=233 cterm=NONE
hi StatusLine guifg=#ede1ff guibg=#10060e guisp=#10060e gui=italic ctermfg=189 ctermbg=233 cterm=NONE
hi Label guifg=#ff4164 guibg=NONE guisp=NONE gui=NONE ctermfg=13 ctermbg=NONE cterm=NONE
hi PMenuSel guifg=#413d5e guibg=#ded6ee guisp=#ded6ee gui=NONE ctermfg=60 ctermbg=255 cterm=NONE
hi Search guifg=#fb8dff guibg=#251730 guisp=#251730 gui=underline ctermfg=213 ctermbg=236 cterm=underline
hi Delimiter guifg=#85e6c6 guibg=NONE guisp=NONE gui=NONE ctermfg=115 ctermbg=NONE cterm=NONE
hi Statement guifg=#93ffe6 guibg=NONE guisp=NONE gui=NONE ctermfg=122 ctermbg=NONE cterm=NONE
hi Comment guifg=#cabfd6 guibg=NONE guisp=NONE gui=italic ctermfg=146 ctermbg=NONE cterm=NONE
hi Character guifg=#ff449e guibg=NONE guisp=NONE gui=NONE ctermfg=13 ctermbg=NONE cterm=NONE
hi Number guifg=#ff449e guibg=NONE guisp=NONE gui=NONE ctermfg=13 ctermbg=NONE cterm=NONE
hi Boolean guifg=#93ffe6 guibg=NONE guisp=NONE gui=NONE ctermfg=122 ctermbg=NONE cterm=NONE
hi Operator guifg=#d4cbff guibg=#151515 guisp=#151515 gui=NONE ctermfg=189 ctermbg=233 cterm=NONE
hi CursorLine guifg=NONE guibg=#15191c guisp=#15191c gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE
hi TabLineFill guifg=#c1bdee guibg=NONE guisp=NONE gui=NONE ctermfg=189 ctermbg=NONE cterm=NONE
hi DiffDelete guifg=#70045e guibg=#220518 guisp=#220518 gui=NONE ctermfg=53 ctermbg=53 cterm=NONE
hi CursorColumn guifg=NONE guibg=#15191c guisp=#15191c gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE
hi Define guifg=#8dffdf guibg=NONE guisp=NONE gui=NONE ctermfg=122 ctermbg=NONE cterm=NONE
hi Function guifg=#ff5e63 guibg=NONE guisp=NONE gui=NONE ctermfg=203 ctermbg=NONE cterm=NONE
hi FoldColumn guifg=#c6fee2 guibg=#363548 guisp=#363548 gui=NONE ctermfg=158 ctermbg=238 cterm=NONE
hi PreProc guifg=#8dffdf guibg=NONE guisp=NONE gui=NONE ctermfg=122 ctermbg=NONE cterm=NONE
hi Visual guifg=NONE guibg=#403f40 guisp=#403f40 gui=NONE ctermfg=NONE ctermbg=238 cterm=NONE
hi VertSplit guifg=#1a0966 guibg=#090618 guisp=#090618 gui=italic ctermfg=17 ctermbg=234 cterm=NONE
hi Exception guifg=#ff4164 guibg=NONE guisp=NONE gui=NONE ctermfg=13 ctermbg=NONE cterm=NONE
hi Keyword guifg=#ff4164 guibg=NONE guisp=NONE gui=NONE ctermfg=13 ctermbg=NONE cterm=NONE
hi Type guifg=#ff4164 guibg=NONE guisp=NONE gui=NONE ctermfg=13 ctermbg=NONE cterm=NONE
hi DiffChange guifg=NONE guibg=#180a20 guisp=#180a20 gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE
hi Cursor guifg=NONE guibg=#98f0e6 guisp=#98f0e6 gui=NONE ctermfg=NONE ctermbg=159 cterm=NONE
hi Error guifg=NONE guibg=#901460 guisp=#901460 gui=NONE ctermfg=NONE ctermbg=89 cterm=NONE
hi PMenu guifg=#e8ddff guibg=#000000 guisp=#000000 gui=NONE ctermfg=189 ctermbg=NONE cterm=NONE
hi SpecialKey guifg=#b9b6ce guibg=#343334 guisp=#343334 gui=NONE ctermfg=146 ctermbg=236 cterm=NONE
hi Constant guifg=#ff449e guibg=NONE guisp=NONE gui=NONE ctermfg=13 ctermbg=NONE cterm=NONE
hi Tag guifg=#d3eb85 guibg=NONE guisp=NONE gui=NONE ctermfg=192 ctermbg=NONE cterm=NONE
hi String guifg=#facc82 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
hi PMenuThumb guifg=NONE guibg=#8fa89e guisp=#8fa89e gui=NONE ctermfg=NONE ctermbg=109 cterm=NONE
hi MatchParen guifg=#e8ddff guibg=#7870a0 guisp=#7870a0 gui=bold ctermfg=189 ctermbg=103 cterm=bold
hi Repeat guifg=#ff4164 guibg=NONE guisp=NONE gui=NONE ctermfg=13 ctermbg=NONE cterm=NONE
hi Directory guifg=#ff9f85 guibg=NONE guisp=NONE gui=NONE ctermfg=216 ctermbg=NONE cterm=NONE
hi Structure guifg=#8dffdf guibg=NONE guisp=NONE gui=NONE ctermfg=122 ctermbg=NONE cterm=NONE
hi Macro guifg=#8dffdf guibg=NONE guisp=NONE gui=NONE ctermfg=122 ctermbg=NONE cterm=NONE
hi DiffAdd guifg=NONE guibg=#090822 guisp=#090822 gui=NONE ctermfg=NONE ctermbg=17 cterm=NONE
hi TabLine guifg=#4e4b4e guibg=#9fc0bd guisp=#9fc0bd gui=italic ctermfg=239 ctermbg=109 cterm=NONE
hi cursorim guifg=#86828c guibg=#6ad0ff guisp=#6ad0ff gui=NONE ctermfg=245 ctermbg=81 cterm=NONE
hi rubyglobalvariable guifg=#ccbfd4 guibg=NONE guisp=NONE gui=NONE ctermfg=182 ctermbg=NONE cterm=NONE
hi operatorcurlybrackets guifg=#3dffe5 guibg=NONE guisp=NONE gui=bold ctermfg=86 ctermbg=NONE cterm=bold
hi rubypredefinedidentifier guifg=#ff49a7 guibg=NONE guisp=NONE gui=NONE ctermfg=205 ctermbg=NONE cterm=NONE
hi user2 guifg=#9d8bee guibg=#35535e guisp=#35535e gui=NONE ctermfg=141 ctermbg=66 cterm=NONE
hi user1 guifg=#e0ffdd guibg=#35535e guisp=#35535e gui=NONE ctermfg=194 ctermbg=66 cterm=NONE
hi mbenormal guifg=#ffbbc1 guibg=#2e373f guisp=#2e373f gui=NONE ctermfg=217 ctermbg=237 cterm=NONE
hi perlspecialstring guifg=#9385ff guibg=#403f40 guisp=#403f40 gui=NONE ctermfg=105 ctermbg=238 cterm=NONE
hi doxygenspecial guifg=#ff7378 guibg=NONE guisp=NONE gui=NONE ctermfg=9 ctermbg=NONE cterm=NONE
hi mbechanged guifg=#ede1ff guibg=#2e373f guisp=#2e373f gui=NONE ctermfg=189 ctermbg=237 cterm=NONE
hi mbevisiblechanged guifg=#ede1ff guibg=#46838f guisp=#46838f gui=NONE ctermfg=189 ctermbg=66 cterm=NONE
hi doxygenparam guifg=#ff7378 guibg=NONE guisp=NONE gui=NONE ctermfg=9 ctermbg=NONE cterm=NONE
hi doxygensmallspecial guifg=#ff7378 guibg=NONE guisp=NONE gui=NONE ctermfg=9 ctermbg=NONE cterm=NONE
hi doxygenprev guifg=#ff7378 guibg=NONE guisp=NONE gui=NONE ctermfg=9 ctermbg=NONE cterm=NONE
hi perlspecialmatch guifg=#9385ff guibg=#403f40 guisp=#403f40 gui=NONE ctermfg=105 ctermbg=238 cterm=NONE
hi cformat guifg=#9385ff guibg=#403f40 guisp=#403f40 gui=NONE ctermfg=105 ctermbg=238 cterm=NONE
hi lcursor guifg=#86828c guibg=#d5ff6a guisp=#d5ff6a gui=NONE ctermfg=245 ctermbg=191 cterm=NONE
hi doxygenspecialmultilinedesc guifg=#faf9f4 guibg=NONE guisp=NONE gui=NONE ctermfg=230 ctermbg=NONE cterm=NONE
hi taglisttagname guifg=#6bdfff guibg=NONE guisp=NONE gui=NONE ctermfg=81 ctermbg=NONE cterm=NONE
hi doxygenbrief guifg=#ff4271 guibg=NONE guisp=NONE gui=NONE ctermfg=13 ctermbg=NONE cterm=NONE
hi mbevisiblenormal guifg=#ffe5e3 guibg=#46838f guisp=#46838f gui=NONE ctermfg=224 ctermbg=66 cterm=NONE
hi doxygenspecialonelinedesc guifg=#faf9f4 guibg=NONE guisp=NONE gui=NONE ctermfg=230 ctermbg=NONE cterm=NONE
hi doxygencomment guifg=#3d18fa guibg=NONE guisp=NONE gui=NONE ctermfg=21 ctermbg=NONE cterm=NONE
hi cspecialcharacter guifg=#9385ff guibg=#403f40 guisp=#403f40 gui=NONE ctermfg=105 ctermbg=238 cterm=NONE
hi pythonimport guifg=#cadeca guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
hi pythonexception guifg=#ede1ff guibg=NONE guisp=NONE gui=NONE ctermfg=189 ctermbg=NONE cterm=NONE
hi pythonbuiltinfunction guifg=#cadeca guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
hi pythonoperator guifg=#a6e5f0 guibg=NONE guisp=NONE gui=NONE ctermfg=159 ctermbg=NONE cterm=NONE
hi pythonexclass guifg=#cadeca guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
hi stringdelimiter guifg=#b48d49 guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
hi rubyregexp guifg=#e8e3ff guibg=NONE guisp=NONE gui=NONE ctermfg=189 ctermbg=NONE cterm=NONE
hi string guifg=#facc82 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
hi constant guifg=#ff449e guibg=NONE guisp=NONE gui=NONE ctermfg=13 ctermbg=NONE cterm=NONE
hi normal guifg=#d4cbff guibg=#151515 guisp=#151515 gui=NONE ctermfg=189 ctermbg=233 cterm=NONE
hi rubyinstancevariable guifg=#99c7ff guibg=NONE guisp=NONE gui=NONE ctermfg=111 ctermbg=NONE cterm=NONE
hi rubyclass guifg=#53e6cd guibg=NONE guisp=NONE gui=NONE ctermfg=79 ctermbg=NONE cterm=NONE
hi identifier guifg=#a7cfff guibg=NONE guisp=NONE gui=NONE ctermfg=153 ctermbg=NONE cterm=NONE
hi comment guifg=#cabfd6 guibg=NONE guisp=NONE gui=italic ctermfg=146 ctermbg=NONE cterm=NONE
hi rubyregexpdelimiter guifg=#9b9faf guibg=NONE guisp=NONE gui=NONE ctermfg=103 ctermbg=NONE cterm=NONE
hi rubyregexpspecial guifg=#ebdbf2 guibg=NONE guisp=NONE gui=NONE ctermfg=255 ctermbg=NONE cterm=NONE
hi function guifg=#ff5e63 guibg=NONE guisp=NONE gui=NONE ctermfg=203 ctermbg=NONE cterm=NONE
hi directory guifg=#ff9f85 guibg=NONE guisp=NONE gui=NONE ctermfg=216 ctermbg=NONE cterm=NONE
hi rubysymbol guifg=#78fffd guibg=NONE guisp=NONE gui=NONE ctermfg=123 ctermbg=NONE cterm=NONE
hi rubycontrol guifg=#7de9ff guibg=NONE guisp=NONE gui=NONE ctermfg=117 ctermbg=NONE cterm=NONE
hi rubyidentifier guifg=#99c7ff guibg=NONE guisp=NONE gui=NONE ctermfg=111 ctermbg=NONE cterm=NONE
